server {
    listen 8080; # Cambiamos a 8080 para alinearnos con el estándar de Cloud Run
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Esto es vital para las rutas de Angular
    }

    # Servir imágenes directamente
    location ~* \.(png|jpg|jpeg|gif|ico|svg|json)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
        try_files $uri =404;
    }
}