# ETAPA 1: Construcción (Build)
FROM node:20-alpine AS builder
WORKDIR /app

# Copiamos manifiestos
COPY package*.json ./
COPY client/package*.json ./client/

# Instalamos dependencias
RUN npm install

# Copiamos código fuente
COPY shared/ ./shared/
COPY client/ ./client/

# Compilamos Angular SSR
WORKDIR /app/client
RUN npm run build -- --configuration production

# ETAPA 2: Servidor de Producción (Node.js)
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# Copiamos la carpeta dist de la app cliente
COPY --from=builder /app/client/dist/client ./dist/client

# Exponemos el puerto
EXPOSE 8080

# Ejecutamos con la ruta exacta desde la raíz de trabajo
CMD ["node", "dist/client/server/server.mjs"]